project:
  type: book
  output-dir: docs

book:
  page-navigation: true
  title: "Julia Tutorial on AI for Mathematical Biology"
  author: "Pengfei Song"
  date: "07/05/2026"
  #cover-image: images/cover.png
  site-url: https://song921012.github.io/Julia_Tutorial_on_AI4MathBiology/
  repo-url: https://github.com/song921012/Julia_Tutorial_on_AI4MathBiology/
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - 1-basics.ipynb
    - 2-neural-networks&optimization.ipynb
    - 3-differential-equations.ipynb
    - 4-neural-differential-equations.ipynb
    - 5-symbolic-regression.ipynb
    - 6-uncertainty-quantification-last-layer-nuts.ipynb
    # - part: "Projects/0-projects.qmd"
    #   chapters:
    #     - "Projects/0-ongoingpapers.qmd"
    #     - "Projects/0-scimlbook.qmd"
    # - "0-summary.qmd"
    # - "0-references.qmd"
  # appendices:
  #   - "0-appendix.qmd"
  page-footer:
    left: "Copyright 2023, Pengfei Song"
    right: This book was built with <a href="https://quarto.org/">Quarto</a>.
    #  - icon: github
    #    href: https://github.com/Song921012

language:
  label:
    fig: "Figure "
    tab: "Table "
    thm: "Theorem "
    lem: "Lemma "
    cor: "Corollary "
    prp: "Proposition "
    def: "Definition "
    exm: "Example "
    exr: "Exercise "
    proof: "Proof "
    remark: "Remark "
    solution: "Solution "
  ui:
    edit: "Edit"
    chapter_name: ["Chapter ", ""]

bibliography: references.bib

execute:
  enabled: false

format:
  html:
    #theme: [sandstone, theme.scs]
    #css: styles.css
    theme:
      light: [sandstone, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [sandstone, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
